config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "pages#home", as: "home"

  resources :programmers, only: [:index, :show]
  resources :languages, only: [:index, :show]

  namespace :admin do
    resources :programmers, except: [:index, :show]
    resources :languages, except: [:index, :show]
  end

end

app/models/language.rb
class Language < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_and_belongs_to_many :programmers
  acts_as_paranoid

  validates :name, length: {in: 1..15}, presence: true, uniqueness: true
end

app/models/programmer.rb
class Programmer < ActiveRecord::Base
  serialize :phone_numbers, Array
  has_and_belongs_to_many :languages
  acts_as_paranoid
  mount_uploader :avatar, AvatarUploader

  validates :first_name, :last_name, length: {in: 2..20}
  # validates :phone_numbers, length: {is: 13}
  validates :email, format: {
                      with: URI::MailTo::EMAIL_REGEXP,
                      message: "Only valid emails allowed",
                    }, uniqueness: true
  validates :first_name, :last_name, :email, :avatar, :date_of_birthday, :phone_numbers, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  protected

  def check_admin
    redirect_to home_path, alert: "You do not have the right." unless current_user.admin?
  end
end

app/controllers/admin/languages_controller.rb
class Admin::LanguagesController < Admin::AdminController
  before_action :set_language, only: %i[edit destroy update]

  def edit
  end

  def new
    @language = Language.new
  end

  def create
    @language = Language.new(language_params)
    if @language.save
      redirect_to @language
    else
      render "new"
    end
  end

  def destroy
    @language.destroy
    redirect_to languages_path
  end

  def update
    if (@language.update(language_params))
      redirect_to @language
    else
      render "edit"
    end
  end

  private

  def language_params
    params.require(:language).permit(:name, :active)
  end

  def set_language
    @language = Language.friendly.find(params[:id])
    redirect_to home_path if @language.nil?
  end
end

app/controllers/admin/programmers_controller.rb
class Admin::ProgrammersController < Admin::AdminController
  before_action :set_programmer, only: %i[edit destroy update]
  before_action :set_languages, only: %i[new edit create update]
  before_action :set_programmerLanguages, only: %i[edit update]

  def new
    @programmer = Programmer.new
  end

  def create
    @programmer = Programmer.new(programmer_params)
    @programmer.language_ids = params[:programmer][:languages]
    if @programmer.save
      redirect_to @programmer
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if (@programmer.update(programmer_params) && @programmer.language_ids = params[:programmer][:languages])
      redirect_to @programmer
    else
      render "edit"
    end
  end

  def destroy
    @programmer.destroy
    redirect_to programmers_path
  end

  private

  def programmer_params
    params.require(:programmer).permit(:first_name, :last_name, :email, :avatar, :date_of_birthday, phone_numbers: [])
  end

  def set_programmer
    @programmer = Programmer.find(params[:id])
    redirect_to home_path if @programmer.nil?
  end

  def set_languages
    @languages = Language.all
    redirect_to home_path if @languages.nil?
  end

  def set_programmerLanguages
    @programmerLanguages = @programmer.languages.map { |language| language.id }
    redirect_to home_path if @programmerLanguages.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def index
    @languages = Language.all
    respond_to do |format|
      format.html
      format.json { render json: @languages }
    end
  end

  def show
    @language = Language.friendly.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/programmers_controller.rb
class ProgrammersController < ApplicationController
  def index
    @programmers = Programmer.includes(:languages).all
    @programmersAndLanguages = []
    @programmers.length.times do |i|
      @programmersAndLanguages[i] = @programmers[i].as_json(methods: :languages)
    end
    respond_to do |format|
      format.html
      format.json { render json: @programmersAndLanguages }
    end
  end

  def show
    @programmer = Programmer.find(params[:id])
    @languages = @programmer.languages.map { |language| language.name }.join(", ")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/programmers_helper.rb
module ProgrammersHelper
end

app/views/admin/languages/_alerts.html.erb
<% @language.errors.full_messages.each do |msg|%>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/admin/languages/edit.html.erb
<h3 class="title">Edit language</h3>
<% if @programmer.errors.any? %>
  <%= render 'alerts' %>
<% end %>
<%= form_for :language, url: admin_language_path(@language) , method: :patch do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control"  %>
  </div>
  <div class="form-check check-margin_bottom">
    <%= f.check_box :active, :class => "form-check-input" %>
    <%= f.label :active, "Active", :class => "form-check-label"%>
  </div>
  <div>
    <%= f.submit "Edit language", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/languages/new.html.erb
  <h3 class="title">Create language</h3>

  <% if @language.errors.any? %>
    <%= render 'alerts' %>
  <% end %>

  <%= form_for :language, url: admin_languages_path do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control" %>
    </div>
    <div class="form-check check-margin_bottom">
      <%= f.check_box :active, :class => "form-check-input" %>
      <%= f.label :active, "Active", :class => "form-check-label"%>
    </div>
    <div>
      <%= f.submit "Create language", :class => 'btn btn-primary' %>
    </div>
  <% end %>

app/views/admin/programmers/_alerts.html.erb
<% @programmer.errors.full_messages.each do |msg|%>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/admin/programmers/edit.html.erb
<h3 class="title">Edit programmer</h3>
<% if @programmer.errors.any? %>
  <%= render 'alerts' %>
<% end %>
<%= form_for :programmer, url: admin_programmer_path(@programmer), method: :patch , html: { multipart: true }  do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :date_of_birthday %>
    <%= f.date_field :date_of_birthday, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone_numbers %>
    <%= f.telephone_field :phone_numbers, :class => "form-control", multiple: true, :value => @programmer.phone_numbers[0] %>
    <%= f.telephone_field :phone_numbers, :class => "form-control phone-retreat", multiple: true, :value => @programmer.phone_numbers[1] %>
    <%= f.telephone_field :phone_numbers, :class => "form-control", multiple: true, :value => @programmer.phone_numbers[2] %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= image_tag @programmer.avatar.url, :class => "image-edit d-block"%>
    <%= f.file_field :avatar, :class => "form-control-file" %>
  </div>
  <p>Lenguages</p>
  <% @languages.each do |language| %>
    <div class="form-check check-margin_bottom">
      <%= f.check_box :languages, {:multiple => true, :class => "form-check-input", :disabled => !language.active, :checked=> @programmerLanguages.include?(language.id) }, language.id, nil %>
      <%= f.label :languages, "#{language.name}", :class=>"form-check-label" %>
    </div>
  <% end %>
  <div>
    <%= f.submit "Edit programmer", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/programmers/new.html.erb
  <h3 class="title">Create programmer</h3>
  <% if @programmer.errors.any? %>
    <%= render 'alerts' %>
   <% end %>
    <%= form_for :programmer, html: { multipart: true }, url: admin_programmers_path  do |f| %>
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :date_of_birthday %>
        <%= f.date_field :date_of_birthday, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :phone_numbers %>
        <%= f.telephone_field :phone_numbers, :class => "form-control", multiple: true %>
        <%= f.telephone_field :phone_numbers, :class => "form-control phone-retreat", multiple: true %>
        <%= f.telephone_field :phone_numbers, :class => "form-control", multiple: true %>
      </div>
      <div class="form-group">
        <%= f.label :avatar %>
        <%= f.file_field :avatar, :class => "form-control-file" %>
      </div>
      <% @languages.each do |language| %>
        <div class="form-check check-margin_bottom">
          <%= f.check_box :languages, {:multiple => true, :class => "form-check-input", :disabled => !language.active}, language.id, nil %>
          <%= f.label :languages, "#{language.name}", :class=>"form-check-label" %>
        </div>
      <% end %>
      <%= f.submit "Create programmer", :class => 'btn btn-primary' %>
    <% end %>

app/views/languages/index.html.erb
<%#= javascript_include_tag 'dataTables', 'data-turbolinks-track' => true %>
<h3 class="title">All languages</h3>
<table id="table_languages" class="table table-striped table-bordered display" style="width:100%">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Slug</th>
      <th>Active</th>
      <th>Details</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Slug</th>
      <th>Active</th>
      <th>Details</th>
    </tr>
  </tfoot>
</table>

app/views/languages/show.html.erb
<h3 class="title">Pogramer</h3>
<p>Name: <span class="font-weight-bold"> <%= @language.name %> </span></p>
<p>Slug: <span class="font-weight-bold">  <%= @language.slug %> </span></p>
<p>Active: <span class="font-weight-bold">  <%= @language.active %> </span></p>
<% if current_user &&  current_user.admin? %>
  <div class="btn-group mr-2">
    <%= link_to 'Edit', edit_admin_language_path(@language), :class => "btn btn-success" %>
  </div>
  <div class="btn-group mr-2">
    <%= link_to 'Delete', admin_language_path(@language), :class => "btn btn-danger", method: :delete, data: {confirm: "Do you really want to delete this language?"} %>
  </div>
<% end %>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body >
    <div class = "container">
      <div class="wrapper">
        <header>
          <div class = "row">
            <h1 class=" col item "><u><%= link_to 'Logo', home_path, :class => "text-secondary font-weight-bold" %></u></h1>
            <div  class="justify-content-end sign">
              <div class="btn-group float-right col item"  role="group">
                <% if current_user %>
                  <div class="btn-group mr-2">
                    <%= link_to 'Sing out', destroy_user_session_path, :class => "btn btn-outline-primary", method: :delete %>
                  </div>
                <% else %>
                  <div class="btn-group mr-2">
                    <%= link_to 'Sing up', new_user_registration_path, :class => "btn btn-outline-primary" %>
                  </div>
                  <div class="btn-group mr-2">
                    <%= link_to 'Sing in', user_session_path, :class => "btn btn-outline-primary" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li <% if params[:controller] == 'pages' && params[:action] == 'home' %>class="active nav-item"<%else %>class="nav-item"<% end %>>
                  <%= link_to "Home", home_path, :class => "nav-link" %>
                </li>
                <% if current_user && current_user.admin? %>
                  <li <% if params[:controller] == 'programmers' && params[:action] == 'new' %>class="active nav-item"<%else %>class="nav-item"<% end %>>
                    <%= link_to "Create programmer", new_admin_programmer_path, :class => "nav-link" %>
                  </li>
                <% end %>
                <li <% if params[:controller] == 'programmers' && params[:action] == 'index' %>class="active nav-item"<%else %>class="nav-item"<% end %>>
                  <%= link_to "Show programmer", programmers_path, :class => "nav-link"%>
                </li>
                <% if current_user && current_user.admin? %>
                  <li <% if params[:controller] == 'languages' && params[:action] == 'new' %>class="active nav-item"<%else %>class="nav-item"<% end %>>
                    <%= link_to "Create language", new_admin_language_path,  :class => "nav-link" %>
                  </li>
                <% end %>
                <li <% if params[:controller] == 'languages' && params[:action] == 'index' %>class="active nav-item"<%else %>class="nav-item"<% end %>>
                  <%= link_to "Show language", languages_path, :class => "nav-link"%>
                </li>
              </ul>
            </div>
          </nav>
        </header>
        <main class="text-secondary">
          <%= render 'layouts/alerts' %>
          <%= yield %>
        </main>
      </div>
      <footer >
        <p class="text-center footer-year">2019</p>
      </footer>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<p><h5>Home page</h5></p>

app/views/programmers/index.html.erb
<h3 class="title">All programmers</h3>
<table id="table_programmers" class="table table-striped table-bordered" style="width:100%">
  <thead>
    <tr>
      <th>id</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Date of birthday</th>
      <th>Phone numbers</th>
      <th>Languages</th>
      <th>Avatar</th>
      <th>Details</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>id</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Date of birthday</th>
      <th>Phone numbers</th>
      <th>Languages</th>
      <th>Avatar</th>
      <th>Details</th>
    </tr>
  </tfoot>
</table>

app/views/programmers/show.html.erb
<h3 class="title">Pogramer</h3>
<p>First name: <span class="font-weight-bold"> <%= @programmer.last_name %> </span></p>
<p>Last name: <span class="font-weight-bold">  <%= @programmer.first_name %> </span></p>
<p>Email: <span class="font-weight-bold">  <%= @programmer.email %> </span></p>
<p>Date of birthday: <span class="font-weight-bold">  <%= @programmer.date_of_birthday.to_s.gsub("-", ".") %> </span></p>
<p>Phone numbers: <span class="font-weight-bold">  <%= @programmer.phone_numbers.delete_if(&:blank?).join(", ") %> </span></p>
<p>Languages: <span class="font-weight-bold">  <%= @languages %> </span></p>
<p>Avatar:
  <%= image_tag @programmer.avatar.url, :class => "image-show d-block"%>
</p>
<% if current_user &&  current_user.admin?%>
  <div class="btn-group mr-2">
    <%= link_to 'Edit', edit_admin_programmer_path(@programmer), :class => "btn btn-success" %>
  </div>
  <div class="btn-group mr-2">
    <%= link_to 'Delete', admin_programmer_path(@programmer), :class => "btn btn-danger", method: :delete, data: {confirm: "Do you really want to delete this programmer?"} %>
  </div>
<% end %>